AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ECS Base Template
Parameters:
  ApplicationEnvironment:
    Type: String
  ApplicationName:
    Type: String
  ECRRepositoryUri:
    Type: String
    Description: Full Uri for consumer docker image to run in container
  CommitHash:
    Type: String
  PortNumber:
    Type: Number
  ListenerArn:
    Type: String
  OrganizationName:
    Type: String
Resources:
  # Role for ECS container
  ContainerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ApplicationName}-${ApplicationEnvironment}-ContainerExecutionRole'
      Description: IAM Role for ECS container
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
        - Key: ApplicationEnvironment
          Value: !Ref ApplicationEnvironment
  # Fargate ECS Service
  MicroService:
    Type: AWS::ECS::Service
    DependsOn: ApiListenerRule
    Properties:
      ServiceName: !Join ['-', [!Ref ApplicationName, !Ref ApplicationEnvironment]]
      Cluster: !Sub '{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:ecs-cluster-name}}'
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Sub '{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:Private-Subnet-A}}'
          SecurityGroups:
            - !Sub '{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:Base-SecGroup}}'
      LoadBalancers:
        - ContainerName: !Ref ApplicationName
          ContainerPort: !Ref PortNumber
          TargetGroupArn: !Ref TargetGroup
  # Fargate Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ApplicationName}-${ApplicationEnvironment}
      RequiresCompatibilities:
        - FARGATE
      Memory: 2048
      Cpu: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub '{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:ecs-task-execution-role}}'
      TaskRoleArn: !Ref ContainerExecutionRole
      ContainerDefinitions:
        - Name: !Ref ApplicationName
          Image: !Join [':', [!Ref ECRRepositoryUri, !Ref CommitHash]] # This gets passed as param from ecs.json generated in buildspec
          PortMappings:
            - ContainerPort: !Ref PortNumber
          Environment:
            - Name: APPLICATION_NAME
              Value: !Sub ${ApplicationName}
            - Name: APPLICATION_ENVIRONMENT
              Value: !Ref ApplicationEnvironment
            - Name: PORT
              Value: !Ref PortNumber
            - Name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              Value: 'com.mysql.cj.jdbc.Driver'
            - Name: SPRING_DATASOURCE_USERNAME
              Value:  '{{resolve:secretsmanager:rds-db-credentials:SecretString:db_username}}'
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: '{{resolve:secretsmanager:rds-db-password:SecretString:rds-db-password}}'
            - Name: SPRING_DATASOURCE_URL
              Value: !Join
                - ''
                - - !Sub 'jdbc:mysql://{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:host}}'
                  - !Sub ':{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:port}}'
                  - !Sub '/{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:dbname}}'
          Essential: true
          Memory: 2048
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/${OrganizationName}/${ApplicationName}/${ApplicationEnvironment}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
              awslogs-create-group: 'true'
  # Optional
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: '/health'
      HealthCheckTimeoutSeconds: 5
      HealthCheckPort: !Ref PortNumber
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Sub '${ApplicationName}-${ApplicationEnvironment}-tg'
      Port: !Ref PortNumber
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      TargetType: ip
      VpcId: !Sub '{{resolve:secretsmanager:${OrganizationName}/${ApplicationEnvironment}/ecs-test-secret:SecretString:vpc-id}}'
  ApiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      ListenerArn: !Ref ListenerArn
      Priority: 10
